import type { Event } from "@/lib/types"

export const events: Event[] = [
  {
    id: "hackathon",
    title: "HackNova",
    description: "24-hour coding challenge to build innovative solutions. Form teams of 3-4 members.",
    longDescription: "24-hour coding challenge to build innovative solutions. Form teams of 3-4 members.",
    rules: [
    "Teams of 3–4 members",
    "24-hour continuous coding",
    "Theme will be revealed at the start",
    "Preliminary round followed by finals",
    "Judging based on innovation, execution, and presentation"
  ],
    category: "cat1",
    formUrl: "https://forms.gle/NLdLHYckW4Vsq2Pr7",
  },
  {
    id: "roboKarts",
    title: "RoboKarts",
    description: "Design and race robotic cars through an obstacle course. Test your engineering skills!",
    longDescription: "Design and ",
    rules: [
      "Teams of 2-3 members",
      "Bring your own robot car or assemble on-site",
      "Three rounds: Time trial, Obstacle course, Battle royale",
      "Cars must be autonomous or remote-controlled",
      "Maximum dimensions: 30cm x 20cm x 15cm"
    ],   
    category: "cat1",
    formUrl: "https://forms.gle/1iQR7YXfuWjux7wy9",
  },
  {
    id: "cicada",
    title: "Cicada",
    description: "Cryptic puzzle-solving challenge that tests your logical thinking and coding skills.",
    longDescription: "Cryptic puzzle-solving challenge that tests your logical thinking and coding skills.",
    rules: ["Individual participation",
      "Multiple rounds of increasing difficulty",
      "Cryptography, steganography, and coding challenges",
      "Time-based scoring system",
      "Hints available with time penalties",],
    category: "cat2",
    formUrl: "https://forms.gle/qCkPevcxJJaptvLX7",
  },
  {
    id: "aiart",
    title: "Prompt+Pixel",
    description: "Create stunning artwork using AI tools in this creative showdown.",
    longDescription: "Create stunning artwork using AI tools in this creative showdown.",
    rules: ["Individual or pairs",
            "Use any AI art generation tool",
            "Theme will be provided on-spot",
             "90 minutes to create and submit",
             "Judging based on creativity, technical skill, and theme interpretation",
    ],
    category: "cat2",
    formUrl: "https://forms.gle/AyKFbPCzzFE9oqTc9",
  },
  {
    id: "techdebate",
    title: "Ctrl+Convince(TECH DEBATE)",
    description: "Argue your stance on controversial tech topics in this heated debate competition.",
    longDescription: "Argue your stance on controversial tech topics in this heated debate competition.",
    rules: ["Teams of 2 members",
            "Topics related to technology ethics and future",
            "Preliminary written round followed by live debates",
            "Oxford-style debate format",
            "Judging based on argument quality, research, and presentation",],
    category: "cat2",
    formUrl: "https://forms.gle/Jd5TSuuQr4bU9onw7",
  },
  {
    id: "ideathon",
    title: "PitchSpark",
    description: "Brainstorm innovative solutions to real-world problems in this idea marathon.",
    longDescription: "Brainstorm innovative solutions to real-world problems in this idea marathon.",
    rules: ["Teams of 3-4 members",
             "8-hour ideation challenge",
             "Problem statements from industry partners",
             "Create business model, prototype, and pitch",
             "Judging based on innovation, feasibility, and impact",
    ],
    category: "cat2",
    formUrl: "https://forms.gle/2JwSmCLHTcz8V1Wh8",
  },
  {
    id: "quickquery",
    title: "QuickBits",
    description: "Test your SQL and database knowledge in this fast-paced query challenge.",
    longDescription: "Test your SQL and database knowledge in this fast-paced query challenge.",
    rules: ["Individual participation",
            "Three rounds of increasing complexity",
            "SQL queries, database design, and optimization",
            "Time-based scoring system",
            "Multiple database systems (MySQL, PostgreSQL, MongoDB)",
    ],
    category: "cat2",
    formUrl: "https://forms.gle/z6UFifRwZCCyFV8KA",
  },
  {
    id: "blankcoding",
    title: "Blank Coding",
    description: "Code without seeing the output until submission. Test your debugging skills!",
    longDescription: "Code without seeing the output until submission. Test your debugging skills!",
    rules: ["Individual participation",
            "No output checking until final submission",
            "Multiple programming languages allowed",
            "Time-based scoring with penalties for errors",
            "Choice of programming language",
    ],
    category: "cat3",
    formUrl: "null",
    registrationType: "onspot",
  },
  {
    id: "techwhisper",
    title: "Tech Whisper",
    description: "Communicate technical concepts without using technical terms in this fun challenge.",
    longDescription: "Communicate technical concepts without using technical terms in this fun challenge.",
    rules: ["Teams of 2 members",
            "Explain technical concepts without using technical terms",
            "Time limit for each explanation",
            "Points awarded for successful communication",
            "Multiple rounds with increasing difficulty",],
    category: "cat3",
    formUrl: "null",
    registrationType: "onspot"
  },
  {
    id: "techpictionary",
    title: "Tech Pictionary",
    description: "Draw and guess technical concepts in this visual challenge.",
    longDescription: "Draw and guess technical concepts in this visual challenge.",
    rules: ["Teams of 3-4 members",
            "Draw technical concepts for teammates to guess",
            "No words or symbols allowed in drawings",
            "Time limit for each round",
            "Points based on speed and accuracy",
    ],
    category: "cat3",
    formUrl: "null",
    registrationType: "onspot"
  },
  {
    id: "techtimesup",
    title: "Tech Time's Up",
    description: "Describe technical terms against the clock in this fast-paced word game.",
    longDescription: "Describe technical terms against the clock in this fast-paced word game.",
    rules: ["Teams of 3 members",
            "Three rounds: describe, one word, charades",
            "30 seconds per term",
            "Technical vocabulary from various domains",
            "Points for each correctly guessed term",
    ],
    category: "cat3",
    formUrl: "null",
    registrationType: "onspot"
  },
  {
    id: "turbotyping",
    title: "Turbo Typing",
    description: "Test your typing speed and accuracy in this keyboard challenge.",
    longDescription: "Test your typing speed and accuracy in this keyboard challenge.",
    rules: ["Individual participation",
            "Multiple rounds with different text types",
            "Code snippets, technical documentation, and prose",
            "Scoring based on WPM and accuracy",
            "Special characters and formatting count",
    ],
    category: "cat3",
    formUrl:"null",
    registrationType: "onspot"
  },
]

export const categoryNames = {
  cat1: "STREAM 1",
  cat2: "STREAM 2",
  cat3: "STREAM 3",
}

export function getEventById(id: string): Event | undefined {
  return events.find((event) => event.id === id)
}

export function getEventsByCategory(category: string): Event[] {
  return events.filter((event) => event.category === category)
}
